name: Deploy to Firebase Functions on merge
'on':
  push:
    branches:
      - main
jobs:
  check:
    name: Check if files
    outputs:
      diff: ${{ steps.check_files.outputs.diff }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check modified files
        id: check_files
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            .github/workflows/firebase-functions-merge.yml
            functions/*
            functions/**/*

  deploy:
    name: Deploy Cloud Functions
    needs: check
    if: needs.check.outputs.diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.20
      - uses: pocket-apps/action-setup-firebase@v2
        with:
          firebase-token: ${{ secrets.FIREBASE_AUTH_TOKEN }}
      - name: Upload
        run: |
          npm install -g yarn
          cd functions
          yarn install --frozen-lockfile
          yarn deploy
          npm uninstall -g yarn
