name: Deploy to Firebase Functions on merge
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/firebase-functions-merge.yml
      - functions/*
      - functions/**/*

jobs:
  deploy:
    name: Deploy Cloud Functions
    if: needs.check.outputs.diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Setup Firebase CLI
        uses: w9jds/setup-firebase@main
        with:
          tools-version: 10.5.0
          firebase_token: ${{ secrets.FIREBASE_AUTH_TOKEN }}

      - name: Upload
        run: |
          npm install -g yarn
          cd functions
          yarn install --frozen-lockfile
          yarn deploy
          npm uninstall -g yarn
