name: Deploy to Firebase Functions on merge
'on':
  push:
    branches:
      - main
jobs:
  check:
    name: Check if files
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check modified files
        id: check_files
        run: |
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file != functions/* ]]; then
              echo "::set-output name=run_job::false"
            else
              echo "::set-output name=run_job::true"
              break
            fi
          done < files.txt

  deploy:
    name: Deploy Cloud Functions
    needs: check
    if: needs.check.outputs.run_job == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.20
      - name: Upload
        run: |
          npm install -g yarn
          cd functions
          yarn install --frozen-lockfile
          yarn deploy
          npm uninstall -g yarn
